(define (problem two_towers)
  (:domain blocksworld)
  (:objects r g b y m c - block)
  (:init
        (clear b)
        (clear c)
        (clear g)
        (clear m)
        (clear r)
        (clear y)
        (handempty)
        (ontable b)
        (ontable c)
        (ontable g)
        (ontable m)
        (ontable r)
        (ontable y)
  )
  (:goal (and (on r g) (on g b) (on y m) (on m c)))
)